In [11]:
import os 
import re
import pandas as pd
import numpy as np

units_df = pd.read_csv('tables/CAIA_Measurement_Unit_Profile.csv')

selected_labs_df = pd.read_csv('tables/OMOP_data_availability_filtered.tsv', sep='\t')
selected_labs_df['SIMPLE_CONCEPT_ID'] = (selected_labs_df['Concept_ID']
                                         .apply(lambda x : re.sub(r'\s+', ' ', re.sub(r'\D', ' ', x)).strip().split(' ')))

In [15]:
unique_lab_units = []
labs_concept_id_dict = selected_labs_df[['Component', 'SIMPLE_CONCEPT_ID']]
for idx, row in labs_concept_id_dict.iterrows():
    units_data_sub = units_df.loc[units_df['MEASUREMENT_CONCEPT_ID'].astype(str)
                                  .isin(row['SIMPLE_CONCEPT_ID'])].copy()
    units_data_sub.loc[:,'LAB_CATCH_ALL'] = row.copy()['Component']
    unique_lab_units.append(units_data_sub[['SITE_ID', 'LAB_CATCH_ALL', 'MEASUREMENT_CONCEPT_ID', 'MEASUREMENT_CONCEPT_NAME', 'UNIT_CONCEPT_ID', 'UNIT_CONCEPT_NAME', 'UNIT_CONCEPT_CODE', 
                                            'RECORD_COUNT', 'MEASUREMENT_RECORD_TOTAL', 'PCT_RECORD_WITHIN_MEASUREMENT', 'PERSON_COUNT', 'MEASUREMENT_PERSON_TOTAL', 'PCT_PERSON_WITHIN_MEASUREMENT']].drop_duplicates())
unique_lab_units = pd.concat(unique_lab_units)

lab_groups = unique_lab_units['LAB_CATCH_ALL'].unique()
# unit_df = unique_lab_units.loc[(unique_lab_units['PCT_RECORD_WITHIN_MEASUREMENT'] > 0.1) & 
#                                (unique_lab_units['PCT_PERSON_WITHIN_MEASUREMENT'] > 0.1)].sort_values(by=['MEASUREMENT_CONCEPT_NAME', 'SITE_ID'])
unit_df = unique_lab_units.sort_values(by=['MEASUREMENT_CONCEPT_NAME', 'SITE_ID'])

# unit_df.to_csv('tables/selected_lab_units.csv', index=False)
unique_lab_units.sort_values(by=['MEASUREMENT_CONCEPT_NAME', 'SITE_ID']).to_csv('tables/full_lab_units.csv', index=False)
# unit_df = pd.read_csv('tables/selected_lab_units.csv')

In [16]:
unique_units = unit_df[['LAB_CATCH_ALL', 'MEASUREMENT_CONCEPT_ID', 'UNIT_CONCEPT_ID', 'UNIT_CONCEPT_NAME', 'UNIT_CONCEPT_CODE']].drop_duplicates()

In [17]:
unique_units['UNIT_RECORD_COUNT'] = np.nan

for i in range(len(unique_units)):
    row = unique_units.iloc[i]
    record_count = unit_df.loc[(unit_df['LAB_CATCH_ALL'] == row['LAB_CATCH_ALL']) &
                               (unit_df['UNIT_CONCEPT_ID'] == row['UNIT_CONCEPT_ID']) &
                               (unit_df['UNIT_CONCEPT_NAME'] == row['UNIT_CONCEPT_NAME']), 'RECORD_COUNT'].sum()
    unique_units.iloc[i, unique_units.columns.get_loc('UNIT_RECORD_COUNT')] = record_count

In [18]:
unique_units.to_csv('tables/unit_counts_full.csv', index=False)

In [38]:
unique_units[['LAB_CATCH_ALL', 'MEASUREMENT_CONCEPT_ID']].drop_duplicates()

                                         LAB_CATCH_ALL  MEASUREMENT_CONCEPT_ID
170                     Alanine Aminotransferase (ALT)                 3006923
741                                            Albumin                 3024561
606                             Albumin/Globulin ratio                 3020509
915                         Alkaline Phosphatase (ALP)                 3035995
243                            Alpha-fetoprotein (AFP)                 3009306
404                   Aspartate Aminotransferase (AST)                 3013721
822                      Direct Bilirubin (conjugated)                 3027597
718                                    Total Bilirubin                 3024128
927                                             Height                 3036277
630                                        Temperature                 3020891
790                                        Body weight                 3025315
599                           C-reactive protein (CRP)                 3020460
157                                            Calcium                 3006906
943                                             CA-125                 3037551
666                                            CA 19-9                 3022914
459                               Carbon Dioxide (CO2)                 3015632
79                      Carcinoembryonic antigen (CEA)                 3003785
432                                           Chloride                 3014576
183         Creatine Kinase Total Activity (CK or CPK)                 3007220
493                                         Creatinine                 3016723
329                           Diastolic blood pressure                 3012888
572  Red Cell Distribution Width (RDW) / erythrocyt...                 3019897
401               Erythrocyte sedimentation rate (ESR)                 3013707
590          Red Blood Cell Count (RBC) / Erythrocytes                 3020416
834                                           Globulin                 3027970
111                                            Glucose                 3004501
812                                          Heartrate                 3027018
693                                   Hematocrit (Hct)                 3023314
34                                    Hemoglobin (Hgb)                 3000963
642               International Normalized Ratio (INR)                 3022217
481                        Lactate dehydrogenase (LDH)                 3016436
651                        Lactate dehydrogenase (LDH)                 3022250
14           White Blood Cell Count (WBC) / Leukocytes                 3000905
95                              Lymphocytes (Absolute)                 3004327
322                  Mean Corpuscular Hemoglobin (MCH)                 3012030
266   Mean Corpuscular Hemoglobin Concentration (MCHC)                 3009744
711                      Mean Corpuscular Volume (MCV)                 3023599
878                               Monocytes (Absolute)                 3033575
375                             Neutrophils (Absolute)                 3013650
763                                     Platelet Count                 3024929
668                                          Potassium                 3023103
363                    Prostate-specific antigen (PSA)                 3013603
620                                      Total Protein                 3020630
899                              Prothrombin time (PT)                 3034426
736                                         Resp. rate                 3024171
550                                             Sodium                 3019550
86                             Systolic blood pressure                 3004249
221                                       Testosterone                 3008893
385                          Blood Urea Nitrogen (BUN)                 3013682
360       Activated partial thromboplastin time (aPTT)                 3013466
530       Activated partial thromboplastin time (aPTT)                 3018677

In [13]:
unit_df.loc[(unit_df['LAB_CATCH_ALL'] == row['LAB_CATCH_ALL']) &
            (unit_df['UNIT_CONCEPT_ID'] == row['UNIT_CONCEPT_ID']) &
            (unit_df['UNIT_CONCEPT_NAME'] == row['UNIT_CONCEPT_NAME'])]

,SITE_ID,LAB_CATCH_ALL,MEASUREMENT_CONCEPT_ID,MEASUREMENT_CONCEPT_NAME,UNIT_CONCEPT_ID,UNIT_CONCEPT_NAME,UNIT_CONCEPT_CODE,RECORD_COUNT,MEASUREMENT_RECORD_TOTAL,PCT_RECORD_WITHIN_MEASUREMENT,PERSON_COUNT,MEASUREMENT_PERSON_TOTAL,PCT_PERSON_WITHIN_MEASUREMENT
170,DFCI,Alanine Aminotransferase (ALT),3006923,Alanine aminotransferase [Enzymatic activity/v...,0,(NULL/0),NaN,4431,3581870,0.1237,1653,220890,0.7483

In [8]:
curated_units = pd.read_csv('tables/measurements_and_units_to_include.csv')

In [9]:
curated_units['LAB_CATCH

,LAB_CATCH_ALL,UNIT_CONCEPT_ID,UNIT_CONCEPT_NAME,UNIT_CONCEPT_CODE,UNIT_RECORD_COUNT,STANDARD_UNIT,NEEDS_CONVERSION,ADDITION_FACTOR,MULTIPLICATIVE_FACTOR
0,Alanine Aminotransferase (ALT),0,(NULL/0),NaN,4431,8645,No,NaN,NaN
1,Alanine Aminotransferase (ALT),8645,unit per liter,[U]/L,9519140,8645,No,NaN,NaN
2,Alanine Aminotransferase (ALT),8923,international unit per liter,[iU]/L,73220,8645,No,NaN,NaN
3,Albumin,0,(NULL/0),NaN,3188631,8713,No,NaN,NaN
4,Albumin,8713,gram per deciliter,g/dL,9939497,8713,No,NaN,NaN
...,...,...,...,...,...,...,...,...,...
116,Testosterone,0,(NULL/0),NaN,45,8817,No,NaN,NaN
117,Blood Urea Nitrogen (BUN),0,(NULL/0),NaN,6803,8840,No,NaN,NaN
118,Blood Urea Nitrogen (BUN),8840,milligram per deciliter,mg/dL,12791426,8840,No,NaN,NaN
119,Activated partial thromboplastin time (aPTT),8555,second,s,2344706,8555,No,NaN,NaN
120,Activated partial thromboplastin time (aPTT),0,(NULL/0),NaN,89404,8555,No,NaN,NaN